Temporarily skip integration test
This test (test_application.py::test_upgrade_local_charm) has been
messing us up for a while by constantly failing our CI with a known
issue :

juju.errors.JujuAPIError: cannot upgrade application "ubuntu" to charm
"local:focal/ubuntu-0": required storage "files" removedq

This temporary change is to get the CI green to make sure we
spot failures due to changes in PRs.